version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data_processor_db
    ports:
      - "5432:5432"

  data-processor:
    build:
      context: ./services/data_processor
      dockerfile: Dockerfile
    env_file:
      - ./env/.env
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./services/data_processor/logs:/app/logs
    restart: unless-stopped

  tg_standard_bot:
    build:
      context: ./services/tg_standard_bot
      dockerfile: Dockerfile
    env_file:
      - ./env/.env
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./services/tg_standard_bot/app/logs:/app/logs
    restart: unless-stopped

  tg_user_bot:
    build:
      context: ./services/tg_user_bot
      dockerfile: Dockerfile
    env_file:
      - ./env/.env
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./services/tg_user_bot/logs:/app/logs
      - ./services/tg_user_bot/media:/app/media
      - ./session_name.session:/app/session_name.session
    restart: unless-stopped
