version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data_processor_db
    ports:
      - "5432:5432"

  data-processor:
    build:
      context: ./services/data_processor
    env_file:
      - ./env/..env
    depends_on:
      - kafka
      - postgres
    volumes:
      - ./services/data_processor/logs:/app/logs
    restart: unless-stopped

  tg_standard_bot:
    build:
      context: ./services/tg_standard_bot
    env_file:
      - ./env/..env
    depends_on:
      - kafka
    volumes:
      - ./services/tg_standard_bot/app/logs:/app/logs
    restart: unless-stopped

  tg_user_bot:
    build:
      context: ./services/tg_user_bot
    env_file:
      - ./env/..env
    depends_on:
      - kafka
      - postgres
    volumes:
      - ./services/tg_user_bot/logs:/app/logs
      - ./services/tg_user_bot/media:/app/media
      - ./session_name.session:/app/session_name.session
    restart: unless-stopped
