services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
    networks:
      - app_network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 15s
      timeout: 10s
      retries: 10

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tg_ubot
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Если нужно, можно сохранять SQL-скрипты в init-db:
      - ./services/db/init-db:/docker-entrypoint-initdb.d
    networks:
      - app_network

  tg_ubot:
    container_name: tg_ubot
    build:
      context: ./services/tg_ubot
    env_file:
      - /home/dev/app/env/tg_ubot.env
    environment:
      SESSION_FILE: /app/session_name.session
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app_network
    volumes:
      - /home/dev/app/session_name.session:/app/session_name.session
      - tg_ubot_state_volume:/app/data  # для хранения state, если нужно

  bot:
    container_name: bot
    build:
      context: ./services/bot
    env_file:
      - /home/dev/app/env/bot.env
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app_network
    volumes:
      - shared_files:/app/files

  xml_worker:
    container_name: xml_worker
    build:
      context: ./services/xml_worker
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app_network
    volumes:
      - shared_files:/app/files

networks:
  app_network:
    name: app_network
    driver: bridge

volumes:
  zookeeper_data:
    driver: local
  zookeeper_log:
    driver: local
  kafka_data:
    driver: local
  pgdata:
    driver: local
  shared_files:
    driver: local
  tg_ubot_state_volume:
    driver: local
