# docker-compose.yml

version: '3.8'

services:
  userbot:
    build: .
    env_file:
      - ./env/env
    volumes:
      - ./logs:/app/logs
      - ./media:/app/media
    depends_on:
      - kafka
    restart: unless-stopped

  kafka:
    image: wurstmeister/kafka:2.13-2.8.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
