version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "echo ruok | nc localhost 2181 | grep imok"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "userbot_instructions:1:1,telegram_chat_messages:1:1,telegram_channel_messages:1:1"
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data_processor_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  tg_user_bot:
    build: ./services/tg_user_bot
    env_file:
      - ./.env/.env
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./services/tg_user_bot/app/logs:/app/logs
      - ./services/tg_user_bot/media:/app/media
    restart: unless-stopped

  tg_standard_bot:
    build: ./services/tg_standard_bot
    env_file:
      - ./.env/.env
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./services/tg_standard_bot/app/logs:/app/logs
    restart: unless-stopped

  data_processor:
    build: ./services/data_processor
    env_file:
      - ./.env/.env
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./services/data_processor/logs:/app/logs
    restart: unless-stopped

  userbot:
    build: ./tg/tg_user_bot
    environment:
      TELEGRAM_API_ID: your_api_id
      TELEGRAM_API_HASH: your_api_hash
      TELEGRAM_PHONE: your_phone_number
      TELEGRAM_CHANNEL_ID: your_channel_id
      TELEGRAM_CHAT_ID: your_chat_id
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CHANNEL_TOPIC: telegram_channel_messages
      KAFKA_CHAT_TOPIC: telegram_chat_messages
      LOG_LEVEL: INFO
      LOG_FILE: /app/logs/userbot.log
      MEDIA_DIR: /app/media
    volumes:
      - ./tg/tg_user_bot/logs:/app/logs
      - ./tg/tg_user_bot/media:/app/media
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped

  data_processor_extended:
    build: ./data_processor
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/data_processor_db
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: telegram_channel_messages
      LOG_LEVEL: INFO
      LOG_FILE: /app/logs/data_processor.log
      MEDIA_DIR: /app/media
    volumes:
      - ./data_processor/logs:/app/logs
      - ./data_processor/media:/app/media
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
