name: Deploy to Hetzner

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository with full history
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetches the entire commit history

      # Step 2: Set up Git for change detection
      - name: Set up Git
        run: git fetch origin main

      # Step 3: Determine changed services and important files
      - name: Determine changed services and important files
        id: changes
        run: |
          # Identify changed services by listing directories only
          CHANGED_SERVICES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- services/ | grep '^services/' | awk -F/ '{print $2}' | uniq | grep -v '__init__.py')
          echo "CHANGED_SERVICES=$CHANGED_SERVICES" >> $GITHUB_ENV

          # Check if docker-compose.yml or deploy.yml has changed
          CHANGED_DOCKER_COMPOSE=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- docker-compose.yml | wc -l)
          CHANGED_DEPLOY_YML=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- .github/workflows/deploy.yml | wc -l)

          if [ "$CHANGED_DEPLOY_YML" -gt 0 ]; then
            echo "FULL_DEPLOY=true" >> $GITHUB_ENV
          elif [ "$CHANGED_DOCKER_COMPOSE" -gt 0 ]; then
            echo "DOCKER_COMPOSE_CHANGED=true" >> $GITHUB_ENV
          fi

      # Step 4: Debugging - Output changed services and files
      - name: Debug Git Diff
        run: |
          echo "CHANGED_SERVICES: $CHANGED_SERVICES"
          echo "DOCKER_COMPOSE_CHANGED: $DOCKER_COMPOSE_CHANGED"
          echo "FULL_DEPLOY: $FULL_DEPLOY"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- services/ docker-compose.yml .github/workflows/deploy.yml

      # Step 5: Install rsync and other dependencies
      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      # Step 6: Set up SSH Agent with the private key
      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 7: Add the server to known_hosts
      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # Step 8: Test SSH connection
      - name: Test SSH Connection
        run: ssh dev@${{ secrets.SSH_HOST }} 'echo "SSH connection established"'

      # Step 9: Install Docker and Docker Compose on the server if not present
      - name: Install Docker and Docker Compose on server
        run: |
          ssh dev@${{ secrets.SSH_HOST }} << 'EOF'
            # Check if Docker is installed
            if ! command -v docker &> /dev/null
            then
              sudo apt-get update
              sudo apt-get install -y ca-certificates curl gnupg lsb-release
              sudo mkdir -p /etc/apt/keyrings
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
              echo \
                "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
                $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              sudo apt-get update
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            fi

            # Check if Docker Compose is installed
            if ! command -v docker compose &> /dev/null
            then
              sudo mkdir -p /home/dev/.docker/cli-plugins/
              sudo curl -SL https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64 -o /home/dev/.docker/cli-plugins/docker-compose
              sudo chmod +x /home/dev/.docker/cli-plugins/docker-compose
            fi
            docker compose version
          EOF

      # Step 10: Add the user to the Docker group
      - name: Add user to Docker group
        run: ssh dev@${{ secrets.SSH_HOST }} "sudo usermod -aG docker dev"

      # Step 11: Create or update the .env file on the server if required
      - name: Create or Update .env file on server
        run: |
          ssh dev@${{ secrets.SSH_HOST }} "mkdir -p /home/dev/app/env"
          ssh dev@${{ secrets.SSH_HOST }} "cat <<EOF > /home/dev/app/env/.env
          TELEGRAM_API_ID=${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH=${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_PHONE=${{ secrets.TELEGRAM_PHONE }}
          TELEGRAM_CHANNEL_ID=${{ secrets.TELEGRAM_CHANNEL_ID }}
          TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
          KAFKA_BOOTSTRAP_SERVERS=kafka:9092
          EOF"

      # Step 12: Deploy changed services or perform a full deploy
      - name: Deploy services
        run: |
          if [ "${{ env.FULL_DEPLOY }}" == "true" ]; then
            echo "Deploying all services due to changes in deploy.yml"
            # List only directories under services/
            SERVICES=$(ls -d services/*/ | xargs -n 1 basename)
          elif [ "${{ env.DOCKER_COMPOSE_CHANGED }}" == "true" ]; then
            echo "docker-compose.yml changed. Deploying all services."
            SERVICES=$(ls -d services/*/ | xargs -n 1 basename)
          elif [ -n "${{ env.CHANGED_SERVICES }}" ]; then
            echo "Deploying changed services: $CHANGED_SERVICES"
            SERVICES=$CHANGED_SERVICES
          else
            echo "No relevant changes detected. Exiting deployment."
            exit 0
          fi

          for service in $SERVICES; do
            echo "Deploying service: $service"
            # Transform folder name to service name in docker-compose.yml
            SERVICE_NAME=$(echo "$service" | sed 's/data_processor/data-processor/')
            
            # Copy microservice code to the server
            rsync -avz --exclude '.git' --exclude '.github' services/$service/ dev@${{ secrets.SSH_HOST }}:/home/dev/app/services/$service/
            
            # Restart the microservice with rebuild
            ssh dev@${{ secrets.SSH_HOST }} "cd /home/dev/app && docker compose up -d --build --force-recreate $SERVICE_NAME" | tee deploy_${service}.log
          done

      # Step 13: Check Docker Compose status
      - name: Check Docker Compose Status
        run: |
          ssh dev@${{ secrets.SSH_HOST }} "cd /home/dev/app && docker compose ps"

      # Step 14: View logs for deployed services
      - name: View Logs for Deployed Services
        run: |
          if [ "${{ env.FULL_DEPLOY }}" == "true" ] || [ "${{ env.DOCKER_COMPOSE_CHANGED }}" == "true" ]; then
            SERVICES=$(ls -d services/*/ | xargs -n 1 basename)
          else
            SERVICES=$CHANGED_SERVICES
          fi

          for service in $SERVICES; do
            echo "Логи сервиса: $service"
            ssh dev@${{ secrets.SSH_HOST }} "cd /home/dev/app && docker compose logs $service --tail 50"
          done
