name: Deploy to Hetzner

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория с полной историей
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Загружает всю историю коммитов

      # Шаг 2: Настройка Git для обнаружения изменений
      - name: Set up Git
        run: git fetch origin main

      # Шаг 3: Определение изменённых микросервисов и важных файлов
      - name: Determine changed services and important files
        id: changes
        run: |
          # Определяем изменения только в папке services/ и исключаем файлы
          CHANGED_SERVICES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- services/ | grep '^services/' | awk -F/ '{print $2}' | uniq | grep -v '^__init__.py$' || true)
          
          # Преобразуем многострочное значение в одну строку, разделяя сервисы запятыми
          CHANGED_SERVICES=$(echo "$CHANGED_SERVICES" | paste -sd "," -)
          
          # Выводим значение для отладки
          echo "Detected changed services: $CHANGED_SERVICES"
          
          # Устанавливаем переменную окружения
          echo "CHANGED_SERVICES=$CHANGED_SERVICES" >> $GITHUB_ENV

          # Проверяем, изменены ли docker-compose.yml или deploy.yml
          CHANGED_DOCKER_COMPOSE=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- docker-compose.yml | wc -l)
          CHANGED_DEPLOY_YML=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- .github/workflows/deploy.yml | wc -l)
          
          # Устанавливаем переменные окружения для полного деплоя или изменения docker-compose.yml
          if [ "$CHANGED_DEPLOY_YML" -gt 0 ]; then
            echo "FULL_DEPLOY=true" >> $GITHUB_ENV
          elif [ "$CHANGED_DOCKER_COMPOSE" -gt 0 ]; then
            echo "DOCKER_COMPOSE_CHANGED=true" >> $GITHUB_ENV
          fi
          
          # Дополнительный вывод для отладки
          echo "CHANGED_DOCKER_COMPOSE=$CHANGED_DOCKER_COMPOSE"
          echo "CHANGED_DEPLOY_YML=$CHANGED_DEPLOY_YML"

      # Шаг 4: Отладка - вывод изменённых микросервисов и списка изменённых файлов
      - name: Debug Git Diff
        run: |
          echo "CHANGED_SERVICES: $CHANGED_SERVICES"
          echo "DOCKER_COMPOSE_CHANGED: $DOCKER_COMPOSE_CHANGED"
          echo "FULL_DEPLOY: $FULL_DEPLOY"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- services/ docker-compose.yml .github/workflows/deploy.yml

      # Шаг 5: Установка rsync и других зависимостей
      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      # Шаг 6: Настройка SSH Agent с использованием секретного ключа
      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Шаг 7: Добавление хоста в known_hosts
      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # Шаг 8: Тестирование SSH подключения
      - name: Test SSH Connection
        run: ssh dev@${{ secrets.SSH_HOST }} 'echo "SSH connection established"'

      # Шаг 9: Создание или обновление .env файла на сервере (если требуется)
      - name: Create or Update .env file on server
        run: |
          ssh dev@${{ secrets.SSH_HOST }} "rm -f /home/dev/app/env/.env"
          
          ssh dev@${{ secrets.SSH_HOST }} "mkdir -p /home/dev/app/env"
          ssh dev@${{ secrets.SSH_HOST }} "echo TELEGRAM_API_ID=${{ secrets.TELEGRAM_API_ID }} > /home/dev/app/env/.env"
          ssh dev@${{ secrets.SSH_HOST }} "echo TELEGRAM_API_HASH=${{ secrets.TELEGRAM_API_HASH }} >> /home/dev/app/env/.env"
          ssh dev@${{ secrets.SSH_HOST }} "echo TELEGRAM_PHONE=${{ secrets.TELEGRAM_PHONE }} >> /home/dev/app/env/.env"
          ssh dev@${{ secrets.SSH_HOST }} "echo TELEGRAM_TARGET_IDS='${{ secrets.TELEGRAM_TARGET_IDS }}' >> /home/dev/app/env/.env"
          ssh dev@${{ secrets.SSH_HOST }} "echo TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} >> /home/dev/app/env/.env"
          ssh dev@${{ secrets.SSH_HOST }} "echo KAFKA_BOOTSTRAP_SERVERS=kafka:9092 >> /home/dev/app/env/.env"

      # Шаг 10: Создание или обновление .env файла для tg_ubot на сервере
      - name: Create or Update tg_ubot .env file on server
        run: |
          ssh dev@${{ secrets.SSH_HOST }} "mkdir -p /home/dev/app/env"
          ssh dev@${{ secrets.SSH_HOST }} "echo TELEGRAM_API_ID=${{ secrets.TELEGRAM_API_ID }} > /home/dev/app/env/tg_ubot.env"
          ssh dev@${{ secrets.SSH_HOST }} "echo TELEGRAM_API_HASH=${{ secrets.TELEGRAM_API_HASH }} >> /home/dev/app/env/tg_ubot.env"
          ssh dev@${{ secrets.SSH_HOST }} "echo TELEGRAM_PHONE='${{ secrets.TELEGRAM_PHONE }}' >> /home/dev/app/env/tg_ubot.env"
          ssh dev@${{ secrets.SSH_HOST }} "echo TELEGRAM_TARGET_IDS='${{ secrets.TELEGRAM_TARGET_IDS }}' >> /home/dev/app/env/tg_ubot.env"
          ssh dev@${{ secrets.SSH_HOST }} "echo KAFKA_BOOTSTRAP_SERVERS=kafka:9092 >> /home/dev/app/env/tg_ubot.env"

      # Шаг 11: заполнение bot.env
      - name: Create or Update bot .env file on server
        run: |
          ssh dev@${{ secrets.SSH_HOST }} "echo TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} >> /home/dev/app/env/bot.env"

      # Шаг 12: Проверка содержимого .env файла
      - name: Verify .env file on server
        run: |
          ssh dev@${{ secrets.SSH_HOST }} "grep TELEGRAM_TARGET_IDS /home/dev/app/env/.env && echo 'Проверка завершена.'"

      # Шаг 13 deploy session_tg
      - name: Decode and upload Telethon session
        run: |
          # 1. Создадим локальный файл session_name.session из секретной Base64 строки
          echo "${{ secrets.SESSION_FILE_BASE64 }}" | base64 -d > session_name.session
      
          # 2. Передадим этот файл на сервер, в /home/dev/app/ (или другую директорию)
          rsync -avz session_name.session dev@${{ secrets.SSH_HOST }}:/home/dev/app/
      
          # 3. Удалим временный файл
          rm session_name.session

      # Шаг 14 После передачи файла сессии
      - name: Restart tg_ubot Service
        run: |
          ssh dev@${{ secrets.SSH_HOST }} "cd /home/dev/app && docker compose restart tg_ubot"

      # Шаг 15: Остановка сервиса Kafka для обеспечения чистого завершения
      - name: Stop Kafka
        run: |
          ssh dev@${{ secrets.SSH_HOST }} "cd /home/dev/app && docker compose stop kafka"

      # Шаг 16: Удаление устаревшего узла /brokers/ids/1 из Zookeeper
      - name: Clean up Zookeeper node for Kafka broker
        run: |
          ssh dev@${{ secrets.SSH_HOST }} "docker exec zookeeper zkCli.sh -server localhost:2181 delete /brokers/ids/1 || echo 'Node /brokers/ids/1 does not exist'"

      # Шаг 17: Установка Docker и Docker Compose на сервере (если не установлены)
      - name: Install Docker and Docker Compose on server
        run: |
          ssh dev@${{ secrets.SSH_HOST }} << 'EOF'
            # Проверка установки Docker
            if ! command -v docker &> /dev/null
            then
              sudo apt-get update
              sudo apt-get install -y ca-certificates curl gnupg lsb-release
              sudo mkdir -p /etc/apt/keyrings
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
              echo \
                "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
                $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              sudo apt-get update
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            fi

            # Проверка установки Docker Compose
            if ! command -v docker compose &> /dev/null
            then
              sudo mkdir -p /home/dev/.docker/cli-plugins/
              sudo curl -SL https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64 -o /home/dev/.docker/cli-plugins/docker-compose
              sudo chmod +x /home/dev/.docker/cli-plugins/docker-compose
            fi
            docker compose version
          EOF

      # Шаг 18: Добавление пользователя в группу Docker
      - name: Add user to Docker group
        run: ssh dev@${{ secrets.SSH_HOST }} "sudo usermod -aG docker dev"

      # Шаг 19: Деплой изменённых микросервисов или полный деплой
      - name: Deploy services
        run: |
          if [ "${{ env.FULL_DEPLOY }}" == "true" ]; then
            echo "Deploying all services due to changes in deploy.yml"
            SERVICES=$(ls -d services/*/ | xargs -n 1 basename | paste -sd "," -)
          elif [ "${{ env.DOCKER_COMPOSE_CHANGED }}" == "true" ]; then
            echo "docker-compose.yml changed. Deploying all services."
            SERVICES=$(ls -d services/*/ | xargs -n 1 basename | paste -sd "," -)
          elif [ -n "${{ env.CHANGED_SERVICES }}" ]; then
            echo "Deploying changed services: $CHANGED_SERVICES"
            SERVICES=$(echo "$CHANGED_SERVICES" | tr ',' ' ')
          else
            echo "No relevant changes detected. Exiting deployment."
            exit 0
          fi

          # Если полный деплой или изменён docker-compose.yml — копируем весь проект и поднимаем всё
          if [ "${{ env.FULL_DEPLOY }}" == "true" ] || [ "${{ env.DOCKER_COMPOSE_CHANGED }}" == "true" ]; then
            rsync -avz --exclude '.git' --exclude '.github' . dev@${{ secrets.SSH_HOST }}:/home/dev/app/
            ssh dev@${{ secrets.SSH_HOST }} "cd /home/dev/app && docker compose up -d --build --force-recreate"
          else
            # Иначе копируем только изменённые сервисы
            for service in $SERVICES; do
              echo "Deploying service: $service"
              rsync -avz --exclude '.git' --exclude '.github' services/$service/ dev@${{ secrets.SSH_HOST }}:/home/dev/app/services/$service/
            done
            ssh dev@${{ secrets.SSH_HOST }} "cd /home/dev/app && docker compose up -d --build --remove-orphans --force-recreate $SERVICES"
          fi
      # Шаг 20
      - name: Recreate PostgreSQL volume if DB changed
        run: |
          # Предполагаем, что сервис называется "db" и в docker-compose.yml у вас он описывает Postgres.
          # Если в вашем docker-compose имя сервиса "postgres" — замените в командах ниже "db" на нужное имя.
          if echo "${{ env.CHANGED_SERVICES }}" | grep -q "db"; then
            echo "Изменения в сервисе db. Перезапускаем контейнер и пересоздаём volume."
            ssh dev@${{ secrets.SSH_HOST }} "cd /home/dev/app && docker compose stop db && docker compose rm -f -v db"
            ssh dev@${{ secrets.SSH_HOST }} "cd /home/dev/app && docker compose up -d db"
          else
            echo "Сервис db не изменялся. Пропускаем пересоздание volume."
          fi

      # Шаг 21: Проверка статуса Docker Compose
      - name: Check Docker Compose Status
        run: |
          ssh dev@${{ secrets.SSH_HOST }} "cd /home/dev/app && docker compose ps"

      # Шаг 22: Просмотр логов для деплоенных микросервисов
      - name: View Logs for Deployed Services
        run: |
          if [ "${{ env.FULL_DEPLOY }}" == "true" ] || [ "${{ env.DOCKER_COMPOSE_CHANGED }}" == "true" ]; then
            SERVICES=$(ls -d services/*/ | xargs -n 1 basename | paste -sd "," - | tr ',' ' ')
          else
            SERVICES=$(echo "$CHANGED_SERVICES" | tr ',' ' ')
          fi

          for service in $SERVICES; do
            echo "Логи сервиса: $service"
            ssh dev@${{ secrets.SSH_HOST }} "cd /home/dev/app && docker compose logs $service --tail 50"
          done

      # Шаг 23: Обеспечение работы Kafka после деплоя
      - name: Ensure Kafka is running
        run: |
          ssh dev@${{ secrets.SSH_HOST }} "cd /home/dev/app && docker compose up -d kafka"

      # Шаг 24: Проверка состояния Kafka
      - name: Wait for Kafka to be healthy
        run: |
          # Запускаем Kafka (если ещё не запущен)
          ssh dev@${{ secrets.SSH_HOST }} "cd /home/dev/app && docker compose up -d kafka"
          
          # Ждём максимум ~2 минуты (24 раза по 5 секунд)
          for i in {1..24}; do
            status=$(ssh dev@${{ secrets.SSH_HOST }} "cd /home/dev/app && docker compose ps --format json" \
              | jq -r '.[] | select(.Service == "kafka") | .Health')
            
            if [ "$status" = "healthy" ]; then
              echo "Kafka is healthy now"
              exit 0
            fi
            echo "Kafka not healthy yet. Waiting..."
            sleep 5
          done
          echo "Timed out waiting for Kafka to become healthy"
          exit 1

      # Шаг 25: Проверка здоровья Kafka
      - name: Check Kafka Health
        run: |
          ssh dev@${{ secrets.SSH_HOST }} "cd /home/dev/app && docker compose exec kafka kafka-broker-api-versions --bootstrap-server localhost:9092"
          echo "Kafka is alive and responding"

      - name: Remove unused Docker volumes
        run: |
          ssh dev@${{ secrets.SSH_HOST }} "docker volume prune -f"
